### PR TITLE
Remove MLIR_XTEN_ENABLE_TORCH option

### PR DESCRIPTION
**Pull request by cferry-AMD**

### CODE REVIEW

**Comment by mgehre-amd** [comment]
I think this flag also disables tests, so this might break `check-aten` when building without torch

**Comment by cferry-AMD** [comment]
Sure; this PR is just an experiment of mine to check what happens if we don't have the flag. I think it's a good idea to keep this flag so that it's still possible to build mlir-xten to just get its IR.

**Comment by mgehre-amd** [comment]
Should we close this PR?

**Comment by cferry-AMD** [comment]
We don't need this, closing.

**Pull request closed without merging**
